version: '3.8'

services:
  web:
    image: vek123/school-django-app:latest
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  react-app:
    image: vek123/school-react-app:latest
    ports:
      - "3000:3000"