version: '3.8'

services:
  web:
#    image: vek123/school-django
    build: .
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: