# Generated by Django 4.2.1 on 2024-04-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainSchool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='auth_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='study_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainSchool.studyclasses'),
        ),
        migrations.AlterField(
            model_name='studyclasses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainSchool.teachers'),
        ),
    ]
