# Generated by Django 4.2.1 on 2024-04-07 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainSchool', '0002_students_auth_id_alter_students_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['second_name']},
        ),
        migrations.AddField(
            model_name='teachers',
            name='auth_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
