# Generated by Django 4.2.1 on 2024-04-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSchool', '0003_alter_students_options_teachers_auth_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='auth_id',
            new_name='auth',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='auth_id',
            new_name='auth',
        ),
    ]
