# Generated by Django 4.2.1 on 2024-04-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSchool', '0004_rename_auth_id_students_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyclasses',
            name='students_amount',
        ),
        migrations.AlterField(
            model_name='studyclasses',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainSchool.teachers'),
        ),
    ]
