# Generated by Django 4.2.1 on 2024-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSchool', '0006_alter_students_study_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
