# Generated by Django 4.2.1 on 2024-04-18 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainSchool', '0009_alter_navigation_options_alter_navigation_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['-position'], 'verbose_name': 'Элемент навигации', 'verbose_name_plural': 'Панель навигации'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Учащийся', 'verbose_name_plural': 'Учащиеся'},
        ),
        migrations.AlterModelOptions(
            name='studyclasses',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RemoveField(
            model_name='studyclasses',
            name='name',
        ),
        migrations.AddField(
            model_name='studyclasses',
            name='class_name',
            field=models.CharField(blank=True, max_length=5, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='position',
            field=models.IntegerField(unique=True, verbose_name='Позиция на сайте'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='students',
            name='auth',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='study_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='mainSchool.studyclasses', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='studyclasses',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainSchool.teachers', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='auth',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='supervisor',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь(1 / 0)'),
        ),
    ]
