# Generated by Django 5.0.4 on 2024-05-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
