# Generated by Django 4.2.1 on 2024-04-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSchool', '0007_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
