# Generated by Django 4.2.1 on 2024-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSchool', '0008_navigation_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='navigation',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
