# Generated by Django 5.0.4 on 2024-05-21 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSchool', '0010_alter_navigation_options_alter_students_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.AlterField(
            model_name='studyclasses',
            name='class_name',
            field=models.CharField(max_length=5, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='auth',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
    ]
